### ISSUE TITLE
onLocationChange not firing for each page change

### ISSUE THREAD

**Issue by ashokkumar88** [futurepress/epubjs-rn#155]
Hi,
I am using the epub with `flow:paginated`. The `onLocationChange` event is not firing for each page change. The total locations is 45 but the event is firing only 8 times. But when i m using `flow:scrolled-continuous` it is firing on each page change.

**Comment by Vandanabisht17** [comment]
@ashokkumar88 
hii,
I am using this library but it's not working with react-native@0.61.4.
I am getting this error
"Cannot find module 'warnOnce' from 'react-native-implementation.js' ".

**Comment by DDushkin** [comment]
+1 anything on this?
